AWSTemplateFormatVersion: 2010-09-09
Description: Hands-on template for VPC
Parameters:
  ProjectId:
    Description: "Project name id."
    Type: String
    AllowedPattern: '^[a-zA-Z0-9-/:-@\[-\`\{-\~]+$'
    ConstraintDescription: "InvalidValue[ProjectId]"
    Default: MyPoject
  EnvironmentType:
    Description: The environment type
    Type: String
    AllowedValues:
      - prod
      - test
    Default: test
    ConstraintDescription: must be a prod or test
Mappings:
  prod:
    MyBucket:
      BucketName: "prd-aljkfjaslkfjlsadkf"
  test:     
    MyBucket:
      BucketName: "test-aljkfjaslkfjlsadkf"
Conditions:
  IsProd: !Equals [!Ref EnvironmentType , "prod" ]
  IsTest: !Equals [!Ref EnvironmentType , "test" ]

Resources:
    TestBucket:
      Type: AWS::S3::Bucket
      Condition: IsTest
      Properties:
        BucketName: !FindInMap [ !Ref EnvironmentType, MyBucket, BucketName ]
        Tags:
          - Key: env
            Value: !Sub "${EnvironmentType}-${ProjectId}"

    ProdBucket:
      Type: AWS::S3::Bucket
      Condition: IsProd
      DeletionPolicy: Retain
      Properties:
        BucketName: !FindInMap [ !Ref EnvironmentType, MyBucket, BucketName ]
        Tags:
          - Key: env
            Value: !Sub "${EnvironmentType}-${ProjectId}"

Outputs:
  TestBuketName:
    Description: "This is a example bucket creation with outputs value"
    Condition: IsTest
    Value: !GetAtt TestBucket.Arn
    Export:
      #!sub
      Name: !Sub "${AWS::StackName}-${AWS::Region}-${EnvironmentType}-MyBucket"
  
  ProductBuketName:
    Description: "This is a example bucket creation with outputs value"
    Condition: IsProd
    Value: !GetAtt ProdBucket.Arn
    Export:
      #!sub
      Name: !Sub "${AWS::StackName}-${AWS::Region}-${EnvironmentType}-MyBucket"
  
      
      
      