AWSTemplateFormatVersion: 2010-09-09
Description: Hands-on template for VPC
Parameters:
  ProjectId:
      Description: "Project name id."
      Type: String
      AllowedPattern: '^[a-zA-Z0-9-/:-@\[-\`\{-\~]+$'
      ConstraintDescription: "InvalidValue[ProjectId]"
      Default: MyPoject
  EnvironmentType:
    Description: The environment type
    Type: String
    Default: test
    AllowedValues:
      - prod
      - test
    Default: test
    ConstraintDescription: must be a prod or test
Mappings:
  prod:
    MyBucket:
      BucketName: "prd_aljkfjaslkfjlsadkf"
 
  test:     
    MyBucket:
      BucketName: "test_aljkfjaslkfjlsadkf"
   
#    VPC:
 #     VpcCidrBlock: 10.1.0.0/16
#    Subnet:
 #     PublicSubnet1: 10.1.1.0/24

Resources:
    MyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !FindInMap [ !Ref EnvironmentType, MyBucket, BucketName ]
        Tags:
          - Key: "env"
          - Value: !Sub "${EnvironmentType}-${ProjectId}"

Outputs:
  BuketName:
    Description: "This is a example bucket creation with outputs value"
    Value: !GetAtt MyBucket.Arn
    #!Ref MyBucket
    #ここを省略すると外部参照ができなくなる。cloudformationのUI上は他の項目は出力される、
    #
    Export:
      #!sub
      Name: !Sub "${AWS::StackName}-${AWS::Region}-${EnvironmentType}-MyBucket"

      
